---
model_load_dir: "./Llama/llama-3.2-1B"
tokenizer_load_dir: "./Llama/llama-3.2-1B"
policy: "behavioral_cloning"
batch_size: 128                             # if gradient_accumulation_steps > 1, this is the micro-batch size
num_return_buckets: 128                     # legacy from deepmind code. not used.
shuffle: True
worker_count: 0                             # 
max_context_length: 1024                    # reduce memory overhead by limiting context lengths



out_dir: 'out'
eval_interval: 2000
log_interval: 10
eval_iters: 100
eval_only: False                          # if True, script exits right after the first eval
always_save_checkpoint: True               # if True, always save a checkpoint after each eval
init_from: 'scratch'                       # 'scratch' or 'resume' or 'gpt2*'

# wandb logging
wandb_log: False                           # disabled by default. Don't want to make an account
wandb_project: 'owt'
wandb_run_name: 'gpt2'                     # 'run' + str(time.time())

# data
dataset: 'lichess_hf_dataset'
gradient_accumulation_steps: 2             # used to simulate larger batch sizes
block_size: 1024                           # number of tokens.
meta: "meta.pkl"
# model
n_layer: 16
n_head: 8
n_embd: 512
dropout: 0.0                               # for pretraining 0 is good, for finetuning try 0.1+
bias: False                                # do we use bias inside LayerNorm and Linear layers?

# adamw optimizer
learning_rate: 0.0003                      # max learning rate
max_iters: 600000                          # total number of training iterations
weight_decay: 0.01
beta1: 0.9
beta2: 0.95
grad_clip: 1.0                             # clip gradients at this value, or disable if == 0.0

# learning rate decay settings
decay_lr: True                             # whether to decay the learning rate
warmup_iters: 2000                         # how many steps to warm up for
lr_decay_iters: 600000                     # should be ~= max_iters per Chinchilla
min_lr: 0.00003                            # minimum learning rate, should be ~= learning_rate/10 per Chinchilla

# DDP settings
backend: 'nccl'                            # 'nccl', 'gloo', etc.

# system
device_type: 'cuda'
device: 'cuda'                             # examples: 'cpu', 'cuda', 'cuda:0', 'cuda:1' etc., or try 'mps' on macbooks
dtype: 'bfloat16'                          # 'float32', 'bfloat16', or 'float16', the latter will auto implement a GradScaler
compile: True                              # use PyTorch 2.0 to compile the model to be faster (jared is temporarily setting to false for debugging purposes.)
